---
title: "data_wrangling_II"
author: "Lorraine Kwok"
date: "October 10, 2019" 
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)
```

## Get some data

read in the NSDUH data
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url) 

## extract first table from a list of 15 tables 

table_list = (drug_use_xml %>% html_nodes(css = "table")) 

tabl_marj = 
  table_list[[1]] %>%
  html_table() %>%
  slice(-1) %>%
  as_tibble()

tabl_marj
```

get harry potter data
```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")
```

```{r}
# copy and paste tag from selector gadget
hp_movie_names = 
  hpsaga_html %>%
  html_nodes(".lister-item-header a") %>%
  html_text()

hp_movie_runtime = 
  hpsaga_html %>%
  html_nodes(".runtime") %>%
  html_text()

hp_movie_money = 
  hpsaga_html %>%
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

hp_df = 
  tibble(
    title = hp_movie_names,
    runtime = hp_movie_runtime, 
    money = hp_movie_money
  )
```

get napoleon dynamite data

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

get data for nyc water consumption 
GET is a core API call

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content("parsed")
```

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

working with BRFSS data

```{r}
brfss_smart2010 = 
  GET("	https://data.cdc.gov/api/views/waxm-p5qv/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

pokemon data

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name
```

